# Generated by Django 2.2.7 on 2021-01-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=200, unique=True)),
                ('photo', models.ImageField(upload_to='images')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('public', 'PUBLIC'), ('private', 'PRIVATE'), ('family', 'FAMILY'), ('friends', 'FRIENDS'), ('party', 'PARTY')], default='public', max_length=7)),
            ],
        ),
    ]
