# Generated by Django 2.2.7 on 2021-01-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0002_image_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.CharField(choices=[('home', 'HOME'), ('kids', 'KIDS'), ('family', 'FAMILY'), ('friends', 'FRIENDS'), ('party', 'PARTY')], default='home', max_length=7),
        ),
        migrations.AlterField(
            model_name='image',
            name='filter',
            field=models.CharField(choices=[('all', 'ALL'), ('home', 'HOME'), ('kids', 'KIDS'), ('family', 'FAMILY'), ('friends', 'FRIENDS'), ('party', 'PARTY')], default='all', max_length=7),
        ),
    ]
